# Name: Adam Petty
# File: download.py
# This file uses the text files generated by books.py and
# goes through the list and downloads the individual books.
# this file prevents duplicates from being downloaded.

import os, urllib, time, random

os.chdir('/mnt/hdd/gutenberg/book#')

xs = []
url = 'https://gutenberg.org/files/'

#for i in range(ord('a'), ord('z') + 1):
with open("books(l).txt", 'r') as f:
	for line in f:
		if ' ' in line:
			j = line.index(' ') + 1
			xs.append(line[j:-2])

os.chdir('/mnt/hdd/gutenberg/l/')
cwd = os.getcwd()

for i in xs:
	os.chdir(cwd)
	time.sleep(random.randrange(3, 8))

	f = urllib.urlopen(url + '%s/%s.txt' % (i, i))
	s = f.read()
	if "404 Not Found" in s[:100]:
		f = urllib.urlopen(url + '%s/%s-0.txt' % (i, i))
		s = f.read()
		if "404 Not Found" in s[:100]:
			f = urllib.urlopen(url + '%s/%s-8.txt' % (i, i))
			s = f.read()

	os.system('mkdir %s' % i)
	os.chdir('/mnt/hdd/gutenberg/l/%s' % i)
	file("%s.txt" % i, "w").write(s)

